### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onBlur' of undefined

### ISSUE THREAD

**Issue by ajsaule** [dgonz64/react-hook-form-auto#18]
### Config:
- "react": "^16.13.1"

This is basically the structure of the component, it is a`<StandardDialog/>` element from Material UI with the form elements as children. Initially I thought it was the `<FieldPropsOverride />` causing the issues because I might have been passing in the wrong props, but upon using the process of elimination I found that it was not in fact `<FieldPropsOverride />` causing the issue, seems to be something within `<Autoform />` element.

````html
   <StandardDialog
        open={toggleOpenDialog}
        onClose={handleCloseModal}
        headerTitleSize="h1"
      >
        <ErrorMessage message={isFormInvalid && "Please fill all fields"} />
        <div className={classes.dialogForm}>
          <Autoform schema={client} onBlur={nothing}>
            {/* <FieldPropsOverride
              label="Name"
              // onChange={handleChangePlan}
              name="name"
            /> */}
          </Autoform>
          //... rest of form, submit and cancel button have been omitted 
       </div>
    </StandardDialog>
````

### Current behaviour: 
- When I hit the button that sets `toggleOpenDialog` to true, the below error crashes the app.
![Screen Shot 2021-07-29 at 12 33 28](https://user-images.githubusercontent.com/49604000/127422567-24bd599c-bca7-4ada-a799-2f8cbe789a88.png)

### Expected behaviour: 
- For the form field to load in the given dialog and be able to input some values into the form for the changeHandler to make updates to the state form. 

This is my first time posting an issue, so I am not sure what else to include. Let me know if it is too brief and I will add any necessary details.

**Comment by dgonz64** [comment]
Thanks for the report! It's very detailed and already gives me a nice place to start. I will take a closer look but in the meanwhile, I have some questions:
* First, could you try removing `onBlur` in the `<Autoform />` component? It's a long shot, but it could be the culprit because unknown props are passed down the chain and may overwrite the internal one. The `onChange` prop is  managed by react-hook-form-auto. I will take steps to avoid the problem if that's the case.
* Not very important, but what is `nothing`? A function?
* Is it possible for you to show the model `client`? You can mangle field names if needed but your case is very interesting and I would like to reproduce it.
* I see you were passing `onChange` in the `<FieldPropsOverride />`. After `1.3.0` it's possible to set the `onChange` in the schema. It doesn't conflict with the internal `onChange` and is provided with many tools to interact with the form state. You can read about it [here](https://github.com/dgonz64/react-hook-form-auto/blob/HEAD/docs/schema-onchange.md). I hope to drop the experimental label this week. Anyway, I will take a look at allowing `onChange` in the `<FieldPropsOverride />`, that may not work at the moment.

**Comment by ajsaule** [comment]
To answer your questions 
- `onBlur` was originally not a prop in the `<Autoform />` I just added it to see if I could get around the `undefined` error. 
- `nothing` is a function `const nothing = () => {console.log('nothing')}` lol. I just put it in there to see if that would stop the error from being thrown and crashing the app 
- Yep sure the model is below, I basically used one of the example snippets of code you had in the documentation. 
````json
export const client = createSchema("client", {
  name: {
    type: "string",
    required: true,
    max: 40
  },
  age: {
    type: "number"
  }
});
````
- Oh ok, but the `onChange` is commented out anyway, so I am pretty confident that was not the issue. Right? 

I was wondering, how could I make contributions to your project? Do you have a backlog somewhere that I could help with? I am an eager frontend developer and am looking to contribute to open source. Cheers

**Comment by dgonz64** [comment]
Looks like a bug in the library then. I will try to have a bite at it later.

Your help would be very appreciated, indeed. I have a backlog locally, I will take a look to see if I have something not too overwhelming there. In the meanwhile, I think actually [rhfa-material-ui](https://github.com/dgonz64/rhfa-material-ui) needs some love. I somewhat managed to make it look ugly, for example I wasn't able to make the inputs full width. To familiarize with _rhfa_ skins you can read [this](https://github.com/dgonz64/rhfa-playground). I think in order to begin you have to fork the project, probably both react-hook-form-auto and rhfa-material-ui.

**Comment by dgonz64** [comment]
I'm unable to reproduce the bug. I tried to be as close as possible to your example. You can try it [here](https://codesandbox.io/s/elegant-archimedes-ixy3t). It may help if you complete this test case to make it fail.

**Comment by Yorkinjon10** [comment]
The same error occuring in the mui [https://mui.com/material-ui/react-checkbox/](url) in [https://formik.org/](url)
